In [1]:
from qpth.qp import QPFunction
import torch
import numpy as np
from torch.autograd import Variable

In [2]:
nz = 3
nineq = 6
neq = 1

In [13]:
Q=np.array([[1.0,-1.0,1.0],
           [-1.0,2.0,-2.0],
           [1.0,-2.0,4.0]])
q=np.array([2.0,-3.0,1.0])
G=np.array([[0.0,0.0,1.0],[0.0,1.0,0.0],[1.0,0.0,0.0],[0.0,0.0,-1.0],[0.0,-1.0,0.0],[-1.0,0.0,0.0]])
h=np.array([1.0,1.0,1.0,0.0,0.0,0.0])
A=np.array([[1.0,1.0,1.0]])
b=np.array([0.5])

In [14]:
q, Q, G, h, A, b = [torch.Tensor(x) for x in [q, Q, G, h, A, b]]

q, Q, G, h, A, b = [Variable(x) for x in [q, Q, G, h, A, b]]
Q.requires_grad = True
q.requires_grad = True
G.requires_grad = True
h.requires_grad = True
A.requires_grad = True
b.requires_grad = True

In [15]:
qpf = QPFunction()
z_hat = qpf(Q, q, G, h, A, b)

In [16]:
z = z_hat.detach().numpy()[0]
z # solution

array([2.9083935e-10, 5.0000000e-01, 1.4169018e-08], dtype=float32)

In [17]:
z_hat.backward(torch.ones(1, nz))

In [18]:
grads = [x.grad.data.squeeze(0).cpu().numpy() for x in [Q, q, G, h, A, b]]

In [19]:
# saving gradients to file
names = ["dQ", "dq", "dG", "dh", "dA", "db"]

for i in range(len(names)):
    print(names[i], np.matrix(grads[i]))

dQ [[-1.0401226e-16 -8.9406967e-08 -2.5422855e-15]
 [-8.9406967e-08  8.9406967e-08 -1.4901160e-08]
 [-2.5422855e-15 -1.4901160e-08 -8.4453928e-16]]
dq [[-3.5762787e-07  1.7881393e-07 -5.9604645e-08]]
dG [[-2.0045814e-15  1.0271260e-15 -3.3409690e-16]
 [-7.4753029e-16  5.5395023e-15 -1.2458824e-16]
 [-4.0345331e-15  2.0172666e-15 -6.7242219e-16]
 [-7.1525585e-07 -5.5631000e-07 -1.1920933e-07]
 [-1.5949481e-14 -1.3291236e-14 -2.6582475e-15]
 [-1.2516974e-06 -8.9407081e-08 -2.0861626e-07]]
dh [[-4.9670588e-17 -1.0331474e-14 -1.5268376e-22  1.8278758e-06
   4.2531954e-14  1.4305116e-06]]
dA [[-7.1554655e-07 -5.0000006e-01 -1.3337831e-07]]
db [[1.0000008]]
