In [61]:
import numpy as np
import cvxpy as cp
from scipy import sparse
import diffcp

In [86]:
A = sparse.csc_matrix((4,3), dtype=np.float64)
A[1, 0]  =  -1.0
A[0, 1]  =  -1.0
A[2, 1]  =  -1.41421
A[3, 2]  =  -1.0

In [87]:
# equivalent to https://github.com/jump-dev/MathOptInterface.jl/blob/master/src/Test/contconic.jl#L2417

cone_dict = {
    diffcp.PSD: [2],
    diffcp.ZERO: 1
}

b = np.array([-1.0, 0.0, 0.0, 0.0])
c = np.array([1.0, 0.0, 1.0])

x, y, s, D, DT = diffcp.solve_and_derivative(A, b, c, cone_dict)
print(x) # MOI.VariablePrimal
print(s) # MOI.ConstraintPrimal
print(y) # MOI.ConstraintDual


dx, dy, ds = D(sparse.csc_matrix(np.ones((4,3))), np.ones(4), np.ones(3))
print(dx)
print(ds)
print(dy)

[0.99999748 1.         0.99999748]
[8.37535865e-17 9.99997481e-01 1.41421000e+00 9.99997481e-01]
[ 1.99999496  1.         -1.41421356  1.        ]
[2.58577489 1.99999496 2.58577489]
[2.37506913e-16 5.85779924e-01 8.28417913e-01 5.85779924e-01]
[10.75732613  3.5857814  -5.07106069  3.5857814 ]
