In [1]:
import numpy as np
import cvxpy as cp
from scipy import sparse
import diffcp

In [2]:
# equivalent to https://github.com/jump-dev/MathOptInterface.jl/blob/master/src/Test/contconic.jl#L789

cone_dict = {
    diffcp.POS: 1,
    diffcp.ZERO: 1,
    diffcp.SOC: [3],
}

# x <- (t,x,y)
# min x
# s.t.  -1/√2 + y ∈ R₊
#        1 - t ∈ {0}
#      (t,x,y) ∈ SOC₃
# slack/s = b-Ax

A = sparse.csc_matrix(np.array([
  [0.0,   0.0  , 1.0],
  [0.0,  -1.0 ,  0.0],
  [0.0,   0.0 , -1.0],
  [-1.0,   0.0,   0.0],
  [0.0,  -1.0,   0.0]
]))
b = np.array([1.0, -0.707107, 0.0, 0.0, 0.0])
c = np.array([1., 0., 0.])

x, y, s, D, DT = diffcp.solve_and_derivative(A, b, c, cone_dict)
print(x) # MOI.VariablePrimal
print(s) # MOI.ConstraintPrimal
print(y) # MOI.ConstraintDual


dx, dy, ds = D(sparse.csc_matrix(np.eye(5,3)), np.zeros(5), np.zeros(3))
print(dx)
print(ds)
print(dy)

[-0.70710656  0.707107    1.        ]
[-3.03619403e-17 -9.15154367e-17  9.99999999e-01 -7.07106562e-01
  7.07107000e-01]
[ 1.414214    1.00000062  1.414214    1.         -1.00000062]
[1.12132144 0.707107   0.70710656]
[-4.82529416e-17 -1.45441595e-16 -2.92893438e-01  1.12132144e+00
  7.07106999e-01]
[ 2.4142175   5.00000557  3.8284315   1.414214   -4.00000495]
