In [95]:
from qpth.qp import QPFunction
import torch
import numpy as np
from torch import nn
from torch.autograd import Variable

In [96]:
# non-homogeneous quadratic objective
#    minimize 2 x^2 + y^2 + xy + x + y
#       s.t.  x, y >= 0
#             x + y = 1

Q = np.array([[4, 1],
              [1, 2]])
q = np.array([1, 1])
G = np.array([[-1, 0], 
              [0, -1]])
h = np.array([0, 0])
A = np.array([[1, 1]])
b = np.array([1])

In [97]:
q, Q, G, h, A, b = [torch.Tensor(x) for x in [q, Q, G, h, A, b]]

q, Q, G, h, A, b = [Variable(x) for x in [q, Q, G, h, A, b]]
Q.requires_grad = True
q.requires_grad = True
G.requires_grad = True
h.requires_grad = True
A.requires_grad = True
b.requires_grad = True

In [98]:
qpf = QPFunction()
z_hat = qpf(Q, q, G, h, A, b)

In [99]:
z = z_hat.detach().numpy()[0]
z # solution

array([0.24999999, 0.75      ], dtype=float32)

In [100]:
z_hat.backward(torch.Tensor([[1.3, 0.5]]))

In [101]:
grads = [x.grad.data.squeeze(0).cpu().numpy() for x in [Q, q, G, h, A, b]]

In [103]:
grads[0]

array([[-0.04999999, -0.05      ],
       [-0.05      ,  0.14999998]], dtype=float32)

In [104]:
dq = grads[1]
dq

array([-0.19999999,  0.19999997], dtype=float32)

In [105]:
grads[2]

array([[ 1.9995194e-09,  6.0004797e-09],
       [-6.6667405e-10, -1.9999926e-09]], dtype=float32)

In [106]:
grads[3]

array([-7.9999998e-09,  2.6666667e-09], dtype=float32)

In [107]:
dA = grads[4]
dA

array([ 0.37499997, -1.0749999 ], dtype=float32)

In [108]:
db = grads[5]
db

array(0.7, dtype=float32)