In [1]:
import torch

In [2]:
x = torch.ones(2,2,requires_grad=True)

In [3]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [4]:
y = x+2

In [5]:
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [6]:
z = y * y * 3

In [7]:
z

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)

In [10]:
out = z.mean()
out

tensor(27., grad_fn=<MeanBackward0>)

In [11]:
out.backward()

In [12]:
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])